version: 0.0.1
metadata:
  code: WORLD-MODULE
  name: world_module
  description: null
environments:
  - name: local
    default: true
    plugins:
      - name: "@restqa/restqapi"
        config:
          url: http://localhost:8081
    outputs:
      - type: html
        enabled: true
      - type: file
        enabled: true
        config:
          path: restqa-result.json
