name: Backend-Tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      DB_DATABASE: world_database
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo systemctl start mysql
          sudo mysql -e 'CREATE DATABASE IF NOT EXISTS `world_database`;  ' -uroot -proot
          sudo mysql -e "USE world_database; 
                        DROP TABLE IF EXISTS messages;

                        CREATE TABLE messages (
                          ID int NOT NULL AUTO_INCREMENT,
                          coordinate_latitude double NOT NULL,
                          coordinate_longitude double NOT NULL,
                          message_text varchar(255) NOT NULL,
                          user_account_id varchar(255) NOT NULL,
                          PRIMARY KEY (ID)
                        );

                        DROP TABLE IF EXISTS  locations ;

                        CREATE TABLE  locations  (
                          location_name  varchar(255) NOT NULL,
                          coordinate_latitude  double NOT NULL,
                          coordinate_longitude  double NOT NULL,
                          fun_facts  text,
                          related_links  text,
                          about  text,
                          image_url  text,
                          access_permission  enum('PUBLIC','PRIVATE') NOT NULL DEFAULT 'PUBLIC',
                          PRIMARY KEY ( location_name )
                        );

                        SHOW TABLES;
                        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mysql';
                        flush privileges;" -uroot -proot
          sudo mysql -e "DROP DATABASE IF EXISTS usersdb;

                        CREATE DATABASE usersdb;

                        USE usersdb;

                        CREATE TABLE items (
                            user_id varchar(255) NOT NULL,
                            item_id varchar(255) NOT NULL,
                            PRIMARY KEY (user_id, item_id)
                        );

                        CREATE TABLE achievements (
                            achievement_id int NOT NULL,
                            user_id varchar(255) NOT NULL,
                            `type` varchar(45) DEFAULT NULL,
                            points int DEFAULT NULL,
                            image varchar(45) DEFAULT NULL,
                            PRIMARY KEY (achievement_id, user_id)
                        );

                        CREATE TABLE friendships (
                            friendship_id int NOT NULL AUTO_INCREMENT,
                            send_id varchar(255) NOT NULL,
                            receiver_id varchar(255) NOT NULL,
                            `status` tinyint NOT NULL DEFAULT 0,
                            PRIMARY KEY (friendship_id)
                        );

                        CREATE TABLE locations (
                            user_id varchar(255) NOT NULL,
                            LocationName varchar(255) NOT NULL,
                            PRIMARY KEY (user_id, LocationName)
                        );

                        CREATE TABLE useraccounts (
                            user_id varchar(255) NOT NULL,
                            displayName varchar(45) NOT NULL,
                            score int NOT NULL DEFAULT 0,
                            leaderboardParticipant tinyint NOT NULL DEFAULT 0,
                            difficulty varchar(45) NOT NULL DEFAULT `Easy`,
                            PRIMARY KEY (user_id)
                        );

                        ALTER USER 'root' @'localhost' IDENTIFIED WITH mysql_native_password BY 'mysql';

                        flush privileges;"



        


          npm install --save-dev jest
          npm test 