name: DB TEST
env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: 

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        sudo mysql -e source ..\backend\world\database_queries\world_database_locations.sql
        sudo mysql -e source ..\backend\world\database_queries\world_database_messages.sql
        sudo mysql -e 'SHOW DATABASES;'