name: Tests

on: [ push ]

jobs:
  tests:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
      - run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE wordpress_test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot