name: Tests

on: [ push ]

jobs:
  tests:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo systemctl start mysql
          sudo ls
          